version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: papabear-mysql-db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=local
      - MYSQL_USER=nikola
      - MYSQL_PASSWORD=tesla

    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

volumes:
  db:
    driver: local
