import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Invoicy</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="w-screen min-h-screen flex">
        <NavigationPane />
        <section className="basis-[85%]">
          <header className="flex w-full px-12 py-4 border-b-2 border-b-gray-400">
            <div className="ml-auto flex items-center gap-4">
              <div className="font-semibold">Gojo Satoru</div>
              <div className="aspect-square w-10 rounded-full bg-pink-500" />
            </div>
          </header>
          <div className="p-12">
            <h2 className="text-3xl font-bold">Dashboard</h2>
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;

const navigations = [
  { name: 'Dashboard', href: '/' },
  { name: 'Clients', href: '/clients' },
  { name: 'Invoices', href: '/invoices' },
  { name: 'Settings', href: '/settings' },
];

const NavigationPane = () => {
  return (
    <div className="p-4 space-y-12 h-screen border-r-gray-400 border-2 grow">
      <h1 className="text-xl font-bold">LOGO</h1>
      <nav className="">
        <ul className="space-y-8">
          {navigations.map(nav => {
            return (
              <li key={nav.name} className="">
                <Link href="#" className="hover:text-blue-500">
                  {nav.name}
                </Link>
              </li>
            );
          })}
        </ul>
      </nav>
    </div>
  );
};
