import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Fazza Courier Hacks</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main></main>
    </>
  );
};

export default Home;


