name: Testing

on: [pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
     steps:
      - name: Checkout
        uses: actions/checkout@v2
         - name: Cypress run
        uses: cypress-io/github-action@v4.0.0 
        with:
          browser: firefox